FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_STRAPI_API_URL=http://host.docker.internal:1339/api
ENV NEXT_PUBLIC_STRAPI_API_URL=$NEXT_PUBLIC_STRAPI_API_URL

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
