declare module 'Cliente' {
  interface Empresa {
    id?: number;
    attributes?: {
      nome?: string | null;
      fantasia?: string | null;
      tipoPessoa?: string | null;
      endereco?: string | null;
      numero?: string | null;
      complemento?: string | null;
      bairro?: string | null;
      cep?: string | null;
      cidade?: string | null;
      uf?: string | null;
      site?: string | null;
      pais?: string | null;
      porte?: string | null;
      simples?: boolean | null;
      ieStatus?: boolean | null;
      status?: boolean | null;
      adFrailLat?: boolean | null;
      adFrailCab?: boolean | null;
      adEspecialLat?: boolean | null;
      adEspecialCab?: boolean | null;
      latFCab?: boolean | null;
      cabChao?: boolean | null;
      cabTop?: boolean | null;
      cxEco?: boolean | null;
      cxEst?: boolean | null;
      cxLev?: boolean | null;
      cxRef?: boolean | null;
      cxSupRef?: boolean | null;
      platSMed?: boolean | null;
      cxResi?: boolean | null;
      engEco?: boolean | null;
      engLev?: boolean | null;
      engRef?: boolean | null;
      engResi?: boolean | null;
      email?: string | null;
      emailNfe?: string | null;
      tablecalc?: string | null;
      maxPg?: string | null;
      forpg?: string | null;
      frete?: string | null;
      CNPJ?: string | null;
      Ie?: string | null;
      fone?: string | null;
      celular?: string | null;
      CNAE?: string | null;
      codpais?: string | null;
      responsavel?: any | null;
      history?: string | null;
      pedidos?: any | null;
      titulo?: string | null;
      vendedor?: string | null;
      fornecedorId?: number | null;
      vendedorId?: number | null;
      codigo?: string | null;
      business?: any | null;
      user?: any | null;
    };
  }
}
